### ISSUE TITLE
paper-ui related

### ISSUE THREAD

**Issue by azim0ff** [openhab/openhab2#238]
Hello friends, I'm working on a binding for my own gadget and I had observed the following with respect to the paper-ui.

1. When defining item/sitemap/thing combo in the config files, it does not show up in the rendered paper-ui control panel. "Thing" is registered under the Things category. Introducing a Thing through discovery works fine. Classic interface picks up the config item without problems.

2. There are some glitches with the initial layout (control boxes covering each other up). However, if one does an in-page refresh (orang-white refresh button in upper RH corner) the layout fixes itself.

3. And lastly, this is probably because paper-ui is still being worked upon, but as long as I'm here I will mention it as anyways. At times the paper-ui screen gets stuck and doesn't update Thing status. Forcing a browser-cache flush + reloading fixes things.

Browser: Firefox 38 32bit Linux (Ubuntu 12.04)

**Comment by kaikreuzer** [comment]
Hi,

regarding 1: The Paper UI shows tabs for all group items that have the tag „home-group“, see e.g. https://github.com/openhab/openhab2/blob/master/distribution/openhabhome/conf/items/demo.items#L4 <https://github.com/openhab/openhab2/blob/master/distribution/openhabhome/conf/items/demo.items#L4>
In order to have items appear on the control UI, you have to assign them to such a group. (this is because the Paper UI (currently) does not support the sitemap concept and thus tries to be clever to choose what is displayed).

For 2 and 3, please be so kind and report these issues at https://github.com/openhab/smarthome/labels/paperui <https://github.com/openhab/smarthome/labels/paperui>.

Best regards,
Kai

**Comment by azim0ff** [comment]
Hi Kai thank you for your response. I see now about the "home group". Couldn't figure out for the life of me what were the two empty tabs, but there they are. I will move 2 and 3 over to the paperui label.
