### ISSUE TITLE
Network Binding : "System Ping" always return true on Mac OS X server

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab2#269]
On Mac OS X Server, the call

proc = new ProcessBuilder("ping", "-t", String.valueOf((int)(timeout / 1000)), "-c", "1", hostname).start();
int exitValue = proc.waitFor();

always returns an exit code 0, even as the host is not reachable, and thus, the corresponding Channel is always updated with "ON". 

strangely enough, when executing the command line as follows

macmini:logs kaladmin$ ping -c 1 192.168.0.51
PING 192.168.0.51 (192.168.0.51): 56 data bytes
 
--- 192.168.0.51 ping statistics ---
1 packets transmitted, 0 packets received, 100.0% packet loss
macmini:logs kaladmin$ echo $?
2

the output is what it should be

**Comment by kaikreuzer** [comment]
@TecSet, Could you look into that?

**Comment by kgoderis** [comment]
Also, when the device is really reachable, you get about 10 updates/second ,whatever is in the refresh interval attribute of the Thing

2015-06-04 19:20:59 - SamsungLivingRoomPing state updated to ON
2015-06-04 19:20:59 - SamsungLivingRoomPing state updated to ON
2015-06-04 19:20:59 - SamsungLivingRoomPing state updated to ON
2015-06-04 19:20:59 - SamsungLivingRoomPing state updated to ON
2015-06-04 19:20:59 - SamsungLivingRoomPing state updated to ON
2015-06-04 19:20:59 - SamsungLivingRoomPing state updated to ON
2015-06-04 19:20:59 - SamsungLivingRoomPing state updated to ON
2015-06-04 19:20:59 - SamsungLivingRoomPing state updated to ON
2015-06-04 19:20:59 - SamsungLivingRoomPing state updated to ON
2015-06-04 19:21:00 - SamsungLivingRoomPing state updated to ON
2015-06-04 19:21:00 - SamsungLivingRoomPing state updated to ON
2015-06-04 19:21:00 - SamsungLivingRoomPing state updated to ON
2015-06-04 19:21:00 - SamsungLivingRoomPing state updated to ON
2015-06-04 19:21:00 - SamsungLivingRoomPing state updated to ON
2015-06-04 19:21:00 - SamsungLivingRoomPing state updated to ON

**Comment by TecSet** [comment]
That is a pretty interesting behaviour. 

@kgoderis I would like you to test the following ping command: 
ping -t (your_timeout / 1000) -c 1 192.168.0.51
Because maybe the timeout itself or its value is the problem.

**Comment by kgoderis** [comment]
Beware that I have not set the timeout in the thing configuration. With the default value from ESH-INF I get:

Karel-Goderis-MacBook-Air-2:~ kgoderis$ ping -t 5 -c 1 192.168.0.51
PING 192.168.0.51 (192.168.0.51): 56 data bytes

--- 192.168.0.51 ping statistics ---
1 packets transmitted, 0 packets received, 100.0% packet loss
Karel-Goderis-MacBook-Air-2:~ kgoderis$ echo $?
2

Will now try the binding with a timeout attribute....

**Comment by kgoderis** [comment]
Thing network:device:samsungkitchen [hostname="192.168.0.51", use_system_ping=true, refresh_interval=10000, timeout=3000]

confirms what you say. With an explicit timeout it seems to work.

**Comment by TecSet** [comment]
To get it right, your first configuration was:
Thing network:device:samsungkitchen [hostname="192.168.0.51", use_system_ping=true, refresh_interval=10000] 
(without a timeout)

**Comment by kgoderis** [comment]
yep

**Comment by TecSet** [comment]
Okay thats strange.

I tried the following configuration on my mac:
network:device:samsungkitchen [hostname="192.168.0.51", use_system_ping=true] 
and I always get the correct return value.

I also checked the default values  which get correctly assigned. So no problem on the binding side.

@kaikreuzer @kgoderis  There's nothing I can do so far. Since the Problem is fixed, this issue may be closed.

**Comment by kgoderis** [comment]
I get a different behaviour on Mac OS X  and Mac OS X Server. On my airbook it works as it should, but it fails on the Server edition. I dunno why….

K

**Comment by TecSet** [comment]
Due to the fact that it works when you specify the parameters there may be something wrong while the configuration is loaded. 

I would like you to test the following network-jar:
https://github.com/TecSet/openhab2/blob/network-test/addons/binding/org.openhab.binding.network/org.openhab.binding.network-2.0.0-SNAPSHOT.jar

Which has an additional logging that for your configuration may look like this:
"192.168.0.51;0;1;60000;5000;true"

For the configuration please only specify the following:
[hostname="192.168.0.51", use_system_ping=true]

Hopefully that will clear things up.

**Comment by kaikreuzer** [comment]
Assuming this is fixed. Feel free to re-open if it is not the case.

**Comment by kgoderis** [comment]
Continued at https://github.com/openhab/openhab2/issues/300
