### ISSUE TITLE
Compat 1.x Test on OpenPaths

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab2#274]
If fails, and the output on the console is 

osgi> ss | grep openp
147	INSTALLED   org.openhab.binding.openpaths_1.7.0.201504160116
true
osgi> start 147
gogo: BundleException: Could not resolve module: org.openhab.binding.openpaths [147]
  Unresolved requirement: Import-Package: org.codehaus.jackson

**Comment by kaikreuzer** [comment]
You could either add the jackson jar to the addons as well or we could think about adding it to the core runtime.

**Comment by watou** [comment]
Other 1.x bindings also require org.codehuas.jackson 1.9.2, including Nest and Ecobee.  @kaikreuzer [said](https://community.openhab.org/t/nest-binding-in-2-0/2086):
> ...create a PR, which adds Jackson to the openHAB 2 TP and to the dependencies feature, so that it ends up in the distribution?

I can do it, but not before I've setup an OH2/ESH dev environment, which I won't get to very soon due to other priorities...

**Comment by kaikreuzer** [comment]
@kgoderis, Could you please verify that OpenPaths now works on OH2?

**Comment by kaikreuzer** [comment]
@watou: I have added the version 1.6.0 of jackson as this is the one in Orbit.
I noticed that Ecobee and Nest show compilation errors with this because of missing methods. So do these bindings really require Jackson 1.9.2? Where do they get it from in openHAB 1?
Please also note https://github.com/openhab/openhab/issues/3149, which prevents these bindings from being resolved in openHAB 2.

**Comment by watou** [comment]
@kaikreuzer: I am fairly certain the Nest and Ecobee bindings require Jackson 1.9.2 features that are not present in 1.6.0.  They resolve to jars provided by [org.openhab.io.rest.lib](https://github.com/openhab/openhab/tree/master/bundles/io/org.openhab.io.rest.lib/lib).

**Comment by kaikreuzer** [comment]
>  They resolve to jars provided by org.openhab.io.rest.lib.

Ah, that's an explanation :-)
Checking openHAB 1, I just notice that it does not bundle Jackson 1.6.0 at all, although it is part of the target platform. So at runtime, it is always resolved from io.rest.lib...
Unfortunately, Eclipse Orbit does not offer version 1.9.2, only 1.6.0. And I do not really like bundling the jar as a lib in openHAB 2. @watou, do you see a chance to downgrade the code of Nest and Ecobee to be compatible with Jackson 1.6.0 as well?

**Comment by watou** [comment]
@kaikreuzer: Is there a modern GSON in openHAB 1?  It would probably be time better spent to try to port Ecobee and Nest bindings to use that instead of losing the 1.9.2 features going back to 1.6.0.  If memory serves, there were non-null (de)serialization features and date/time handling that were not part of the earlier Jackson versions.  Also, Jackson 1.9.2 was still short of the 2.x features I had wanted to use for proper date/time handling, but since 1.9.2 was provided in org.openhab.io.rest.lib, I felt I had to use it.  I *believe* that GSON will be able to cover all needed features (based on a quick reading of some tutorials).  From my perspective, providing Jackson 1.9.2 for OH1 binding compatibility would be ideal in the interim to avoid any code changes (if any way possible).

**Comment by kaikreuzer** [comment]
No, there is no gson in openHAB1, but in openHAB2, this is the suggested lib to use for json processing. So in the light of a future migration of the bindings to openHAB 2, it might make sense to do this change (and add gson to openHAB1 as well). But as I cannot assess the efforts and risks involved, adding 1.9.2 in openHAB 2 compat layer is probably the easier and safer solution. I'll look into it and reopen this issue for this.

**Comment by kaikreuzer** [comment]
Ok, done! Now you have Jackson 1.9.2 available in the compat layer. Together with https://github.com/openhab/openhab/pull/3150, I would expect that all these bindings now work on OH2. Would be great if you could test it some when!
