### ISSUE TITLE
Please set Due Date for 2.0.0 Beta milestone

### ISSUE THREAD

**Issue by SharpNoiZy** [openhab/openhab2#343]
Hi,
just the wish for a date when the Beta is ready.
I think many "normal" users will start to work with version 2 when it's beta, I will :)

Kind regards

**Comment by cdjackson** [comment]
The release schedule that was released a while ago is to release oh2 beta at the same time as oh1 1.8 release. This should be October or November.

**Comment by kaikreuzer** [comment]
Hi @SharpNoiZy,

I cannot set any due date, since this date depends on YOU, see https://community.openhab.org/t/we-need-your-help-on-testing/298.

So if you want to see a beta soon, help making the code stable and test and fix the backward compatibility. Note that I am almost working alone on openHAB 2 in my little spare time, so reaching new releases is only feasible through the help of the community. Can I count on you?

**Comment by snickers2k** [comment]
@kaikreuzer i would really love to switch from fhem to openhab2 .. It's really awesome. So i would really like to check out openhab2 and maybe inform about issues. But first of all, i can't find a proper install guide :/ Or is it not ready for (test willing) end-users yet? At least with the beta release, i would really appreciate an install guide for end-users. thx

**Comment by udo1toni** [comment]
Here's what you searched for... :) https://github.com/openhab/openhab2/blob/master/docs/sources/intro.md (follow the Links inside Document)

**Comment by angelrr7702** [comment]
I create a docker container for openhab 2.0.0alpha2

https://github.com/QuantumObject/docker-openhab

it will install with the demo. I'm new with respect to openhab , I don't have idea how practical will be running from container and there a lot of stuff i don't know about openhab  but you can used to check it out before you decide to deploy or you can used this container for reference to make your own container or deployment .  You can used for the version 1.7.1 too .. using the tag 1.7.1 

  docker run -d -p xxxx:8080 --link some-mysql:db quantumobject/docker-openhab:1.7.1

**Comment by angelrr7702** [comment]
For 2.0.0alpha2 you don't need to add tag 

docker run -d -p xxxx:8080 --link some-mysql:db quantumobject/docker-openhab

that will install the latest and in this case it is  2.0.0alpha2.

**Comment by snickers2k** [comment]
Thank you guys. 
Only problem was that i tried "servername:8080/openhab.app" insteat of only :8080 

But now my next question; when will openhab2 get to the point where it reaches the goal of "user-friendly for 'regular' " ?
Because i installed the addons-pack manually and still; only thing working in WebUI out of the box is to add Groups. I thought openhab2 is meant to be WebUI only. But in fact, for me, it seems (at least right now) that it still needs more work outside the WebUI than even FHEM does.. Which is kind of the direct opposite of what the actual goal with openhab2 is, right ? 
So since i'm looking for an easier (not worse) solution then FHEM, is there any planning on when it's working to manage openhab2 with just the WebUI ?

thanks

**Comment by kaikreuzer** [comment]
> when will openhab2 get to the point where it reaches the goal of "user-friendly for 'regular' users" ?

At the moment when enough people have contributed to the project to reach that goal. Any planning is futile if you do not know what people are about to contribute.

> I thought openhab2 is meant to be WebUI only.

No, definitely not, but Web becoming one option. Btw, I thought we have that for long in place with HABmin already...

**Comment by snickers2k** [comment]
Okay, thanks. I overlooked HABmin, i guess. Looks really great. Will try it.

**Comment by mickey4u** [comment]
Please I cannot edit the configuration parameters for my binding using the paper ui in the openhab 2 beta release
