### ISSUE TITLE
Latest in eclipse smart home breaks homematic binding

### ISSUE THREAD

**Issue by patrickse** [openhab/openhab2#408]
The commit eclipse/smarthome@6342457c64d008e48bcba859cbc848a51876be1f breaks the homematic binding. Looks like the handling of channelTypes changed. 

I´ve tried to fix it on my own. :( but I failed.

Here´s the maven failure:

```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:0.22.0:compile (default-compile) on project org.openhab.binding.homematic: Compilation failure: Compilation failure:
[ERROR] /Users/patrick/Documents/dev/openhab2/addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/type/ThingTypeGenerator.java:[177]
[ERROR] return new ChannelDefinition(channelTypeUID.getId(), channelType);
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The constructor ChannelDefinition(String, ChannelType) is undefined
[ERROR] /Users/patrick/Documents/dev/openhab2/addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/type/ThingTypeGenerator.java:[283]
[ERROR] ChannelType type = cd.getType();
[ERROR] ^^^^^^^
[ERROR] The method getType() is undefined for the type ChannelDefinition
[ERROR] 2 problems (2 errors)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :org.openhab.binding.homematic
```

Regards,
Patrick

@gerrieg

**Comment by kaikreuzer** [comment]
Indeed - probably time to soon move the Homematic binding to the official repo, then I would have noticed this problem as well :-)

@gerrieg: Nonetheless, the new ChannelTypeRegistry might be very helpful to you as well in order to dynamically construct Things - that's the main purpose of it, so that you can have a static set of channel types defined in XML (which should be pretty static for Homematic), and then dynamically define Things with channels of these types. Let me know if you have any questions regarding this change and how to best adapt your code.

**Comment by gerrieg** [comment]
@patrickse 
i've updated my repository with the changes

@kaikreuzer 
i would prefer a full dynamic generation of the ChannelTypes too. If i have a static set, i have to maintain the XML definitions. With every new device and/or firmware update of an existing device i have to validate the definitions and update them. With Homegear, it's nearly impossible to maintain the XML, because there are much more devices available if a new device family is included.
All required metadata (except the full device names) are available on the gateways. If it's OK for you, i would like to keep the metadata generation as it is.

**Comment by kaikreuzer** [comment]
> i would prefer a full dynamic generation of the ChannelTypes too.

This is also possible with the newly introduced ChannelTypeProviders.

> If it's OK for you, i would like to keep the metadata generation as it is.

As there is no PR for the binding, I actually never had a look so far at the code. So I don't know how the metadata generation is currently done, but have a look yourself at the ChannelTypeProvider and decide whether this is a concept that could be of help.

**Comment by patrickse** [comment]
Just tested the current version and now everything compiles and runs fine on my raspberry.

I just added a few valve drives to my setup and it´s working.

:+1: 

Thanks,
Patrick
