### ISSUE TITLE
ui.cometvisu: Editor didn't find the config file

### ISSUE THREAD

**Issue by steand** [openhab/openhab2#477]
@peuter for your work list 

If I put the config file of cometvisu in the folder: $OPENHAB_HOME/conf/cometvisu the editor of cometvisu didn't find the config file:
`ERROR: config-file does not exist nor demo is known with that name '/home/openhab/CometVisu/src/config/visu_config_testhouse.xml' ('../config/visu_config_testhouse.xml').`

**Comment by peuter** [comment]
Two PR are created to fix this issue (CometVisu also needs to be enhanced to fix this).

One note: Your config file need an aditional oh_ suffix otherwise it is not possible to use the editor. e.g.
$OPENHAB_HOME/conf/cometvisu/config/visu_config_oh_testhouse.xml

I will add this hint to the documentation as soon as both PR's have been merged.
