### ISSUE TITLE
Service Wrapper does not work

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab2#495]
Trying to register the openHAB Karaf instance as a system service as described in https://karaf.apache.org/manual/latest/users-guide/wrapper.html, the files are generated in userdata/bin, but they point to runtime/karaf//bin - it seems as if something gets mixed up with the paths.

**Comment by dvanherbergen** [comment]
When starting karaf as a service, it ignores the setenv script. This causes openHAB to not function correctly. With a new version of the java service wrapper, we would be able to launch the setenv using a prejvmlaunch event. Issue opened: https://issues.apache.org/jira/browse/KARAF-4186

**Comment by kaikreuzer** [comment]
... and closed again :-(

**Comment by dvanherbergen** [comment]
Indeed. This means we'll need a different approach. The first two that come to mind are:
* Use a custom installation command rather than the standard one, e.g. openhab-wrapper:install. Underneath, this could then perform the standard install and perform a config customisation step.
* Stick with the standard install, but move the environment properties out of the setenv and set them programmatically at runtime start.

IMHO, the benefit of the first one is that it could be installed in a single step. The downside would be that users may try to install using the default install, which won't work.
The second approach would just be the opposite. Standard install could be used, but then when the system is first started and makes config changes, it may require a restart for the properties to be applied correctly. Thoughts?

**Comment by kaikreuzer** [comment]
The first options sounds more tempting to me and by documenting it, its downside should not be relevant.

**Comment by dvanherbergen** [comment]
First option it is. I'll see if I can cook up something.

**Comment by dvanherbergen** [comment]
I've created a first version of an openHab installer that wraps the karaf service. However, when testing I found that it works fine on OS X and doesn't work on a raspberry pi v1 (ARMv6 - https://issues.apache.org/jira/browse/KARAF-2734). Even on Windows 7 the default karaf service doesn't work properly... :disappointed: 
Alternatives to JSW are http://yajsw.sourceforge.net/ or http://commons.apache.org/proper/commons-daemon/. Should we stick with the default or change?

**Comment by kaikreuzer** [comment]
Hrmpf, the service wrapping was one of the main features why I liked switching to Karaf...
I had already seen that it does not work on ARMv6, but I think it is ok to require AMRv7 nowadays, so that is not a blocker for me. Do you have a reference regarding Windows 7 problems? Does it at least work on Win 8/10?
I have no idea, how much effort it would mean to switch to another wrapper. If it were easy, I guess Karaf would have switched already... So if we go for something else, maybe it should be suggested to Karaf directly.

**Comment by dvanherbergen** [comment]
The pi1 seems to be too slow for openHAB anyway.. 
I'm wondering if the windows 7 issues may be related to my machine, it's security settings are rather strict. 
I don't have access to a windows 8/10 machine, so I can't verify those.
I've created a PR which contains the openHAB command. It calls the karaf install service internally and then updates the config files, so it should work on all platforms where the default Karaf service works..
I've also changed the KARAF_BASE to point to KARAF_HOME as the Karaf wrapper installs binaries in KARAF_BASE/bin.
