### ISSUE TITLE
UI dev wanting to help

### ISSUE THREAD

**Issue by GradyD** [openhab/openhab2#582]
Hey everyone,

I'm a UI dev that would love to help out on this project. The downside is that I am not really a java dev. It looks like you guys are using java with jetty to server up the web app, service oriented architecture?. Has there been any discussion of moving to a REST based API with node for the UI? Mainly decouple the UI and the business logic, if you are familiar with what Netflix has been doing that is what I am referring to, http://nodesummit.com/media/integrating-node-js-into-your-ecosystem/.

I'd love to help out but I am still trying to wrap my head around how the UI works. So any insight would be helpful.

Thanks

![image](https://cloud.githubusercontent.com/assets/994964/12025596/a7cb25fe-ad7e-11e5-93a3-848578a21932.png)

![image](https://cloud.githubusercontent.com/assets/994964/12025617/c3fa8cf6-ad7e-11e5-8bd5-b400119b2124.png)

**Comment by kaikreuzer** [comment]
Hi @GradyD,

I would love to have more UI developers on board!
I am not completely sure what node.js would bring as a benefit though. Afaik, it is the "headless server" part, which would somehow conflict with the openHAB runtime itself.
Note that openHAB decouples the UI through a REST API already, see https://www.eclipse.org/smarthome/documentation/features/rest.html.
All "modern" openHAB UIs (Paper UI, Basic UI, Android & iOS app) use this REST API and there is no Java code involved at all for the UI; the only thing that needs to be done for pure web UIs (like the Paper UI and the Basic UI) is that they are packaged into an jar, so that they can be served through Jetty on the runtime.

**Comment by GradyD** [comment]
Since this is not really an application of scale I should have just referred to using an API based UI. Node would allow a light weight web server to be spun up but since you already have to spin up the jetty server for the REST APIs it makes sense to couple these together.

Thanks for that link. I did some reading on the REST API as well as looking into the eclipse smartHome repo where I found the paper UI and a few others. 

I think this is enough to get me going. As far as 2.0 do you have a TODO or feature list you are working off of?

**Comment by kaikreuzer** [comment]
Eclipse SmartHome is indeed the right place to look at - the code of the UIs is located there.
We are tracking the bugs and todos there as well, see
https://github.com/eclipse/smarthome/labels/PaperUI and https://github.com/eclipse/smarthome/labels/BasicUI

Wrt current activities on openHAB 2, you might also want to read and follow https://community.openhab.org/t/merry-christmas-and-a-brief-outlook-on-2016/. I am currently doing some major refactorings, which I hope to have finished within the next two weeks.

**Comment by kaikreuzer** [comment]
What I forgot: Let us discuss any further discussion on https://www.eclipse.org/forums/index.php/f/271/ - so feel free to come up with ideas about new UIs or features for the existing UIs there.
