### ISSUE TITLE
Execution order of files

### ISSUE THREAD

**Issue by kalbun** [openhab/openhab2#76]
oH 2.0 seems now to load the "rules" file before the "items" file.

This brings to a lot of "cannot be resolved" errors during the execution of startup rules.

**Comment by Rossko57** [comment]
New User to OpenHAB (wonderful tool!) coupled with nil java experience - so my "contribution" here may be valueless.
Playing with v1.6.2 .... played around in openhab.cfg extending folder scan refresh to 20
(thinking that this does not need to be very frequent in an operational system - perhaps I misunderstand the purpose)
This provoked the error described - rules triggered on 'System started' condition failing during actions because the associated Items do not yet exist.    It causes me a problem because those rules have failed, or more precisely the required actions have not been carried out.
Restoring the folder refresh to 10 circumvents the whole thing (though of course effects could vary with config complexity and host performance)
Just for information !

**Comment by kaikreuzer** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=423516 has been fixed meanwhile
