### ISSUE TITLE
Astro Binding

### ISSUE THREAD

**Issue by gerrieg** [openhab/openhab2#87]
work started

**Comment by gerrieg** [comment]
stopped working, waiting for:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=456212
https://bugs.eclipse.org/bugs/show_bug.cgi?id=456213
https://bugs.eclipse.org/bugs/show_bug.cgi?id=456214

Current state is in my github repo: https://github.com/gerrieg/openhab2/tree/astro/addons/binding/org.openhab.binding.astro
Only calculation and state update works, no events so far.

**Comment by kaikreuzer** [comment]
Thanks for the update!
After our latest (private) discussions, where exactly do you still have the need for https://bugs.eclipse.org/bugs/show_bug.cgi?id=456213?

**Comment by gerrieg** [comment]
If the general DataTime triggers will be implemented, i don't need this issue anymore. I'll watch what comes and will finish the binding then.

**Comment by kaikreuzer** [comment]
Hm, this can take a while, as it depends on the new rule engine implementation.
Maybe you want to finish a "simple" version without the triggers now and enhance it later on?
In the meantime, it might make sense if the 1.x binding works through the compat layer, so that this can be used for the "full" functionality.

**Comment by gerrieg** [comment]
OK, if you prefer this i will make a PR in the next few days.

**Comment by kaikreuzer** [comment]
Added through https://github.com/openhab/openhab2/pull/113
