### ISSUE TITLE
Zoneplayer's support of volume slider does not work as expected

### ISSUE THREAD

**Issue by wolter** [openhab/openhab2#97]
Hi, not sure if this issue is related to #31 and #32, but the usage of the classic dimmer controls (both classic ui and paper ui) does not work as expected. If you turn off and on the volume, it will set to 100% and not restore the previous setting. Just using the slider and the usual on/off control seems to work.

**Comment by kaikreuzer** [comment]
Yes, this is related to #31 and #32. Please try to isolate problems before reporting bugs. Using UIs to test a binding never clearly tells whether the problem is in the UI or the binding and thus assignment of such an issue to the right person is not possible. Better use console commands when testing bindings.

**Comment by wolter** [comment]
Thanks fpr the feedback. Where do I find instructions on this console commands?

**Comment by kaikreuzer** [comment]
Right here: https://github.com/openhab/openhab/wiki/Feature-Overview#osgi-console
As mentioned in https://github.com/openhab/openhab2/blob/master/docs/sources/installation/intro.md#introduction-to-openhab-2, the command is now "smarthome" instead of "openhab", though.
